TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/SSAStorageRingSup/devSSAStorageRing.db
DB_INSTALLS += $(TOP)/SSAStorageRingSup/devSSAStorageRing.proto

#=======================================
include $(TOP)/configure/RULES
