TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/SSABoosterSup/devSSABooster.db
DB_INSTALLS += $(TOP)/SSABoosterSup/devSSABooster.proto

#=======================================
include $(TOP)/configure/RULES
